<?php if ($this->isEnabled()): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function() {
            var config = {
                cookieName: '<?php echo($this->getCookieName()); ?>',
                merchantId: '<?php echo($this->getMerchantId()); ?>',
                scarabJsApiId: 'scarab-js-api',
                scarabSource: '<?php echo($this->getScarabJsUrl()); ?>',
                sendEmail: <?php echo($this->getSendEmail()); ?>,
                testMode: <?php echo($this->isTestMode()); ?>,
                sendParentSku: <?php echo($this->shouldSendParentSku()); ?>,
                subscribeUrl: "<?php echo $this->getSubscriptionUrl();?>",
                formKey: "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>",
                sendWebsiteCode: <?php echo $this->getSendWebsiteCode() ?>,
                websiteCode: "<?php echo Mage::app()->getWebsite()->getCode() ?>"
            };

            aligentEmarsys = new Aligent.Emarsys(config);
        });
    </script>
<?php endif; ?>